import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { PageProps } from '../../.next/types/app/about/page';
import Navbar from "./components/navbar";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
  children:React.ReactNode;
}>) {
   return (
   <html lang="en">
       <body
         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      
        <Navbar />
        
         {/* Main Content */}
        <main className="flex-grow container mx-auto p-4 pb-56"> 
          <div className="bg-white shadow-lg rounded-lg p-6">
            {children}
          </div>
        </main>  

        {/* Footer */}
        <footer className="bg-gray-800 text-white p-4 text-center">
          <p>© 2024 My Website. All rights reserved.</p>
        </footer>


      </body>
    
    </html>
  );
}
